### ISSUE TITLE
Publish compiled js

### ISSUE THREAD

**Issue by Climax777** [lmaccherone/DoublyLinkedList#3]
Hi

I'm still making use of this great library, but for some reason when using `coffee-script/register` along with my ES6 libraries the source maps get twisted.

I would like to ask if this can be published to npmjs with prebuilt js files? I've noticed the Cakefile has such a publish facility?

**Comment by lmaccherone** [comment]
I'm glad you like it. All of my newer projects do what you ask. I'm a bit surprised I don't do it on this one but it sorta makes sense as I haven't done much with this in a good long while. When do you need it by?

**Comment by Climax777** [comment]
The strange thing is that your last commit hints that it has already been
done. There isn't a great deal of rush required. It just makes my debugging
a bit difficult. I guess the real issue lies with coffeescript/babel
breaking source maps.

Thanks!

**Comment by Climax777** [comment]
Hi any progress on this update?

**Comment by lmaccherone** [comment]
Had some time today while watching football so this should now be fixed in v1.0.5

**Comment by Climax777** [comment]
Thanks Larry! Much appreciated!
